spring.application.name=Curso de SpringBoot
server.port=1234
server.servlet.context-path=/ecommerce/api/v1

service.products=listResourceService

#Configuraciones de la aplicación
app.name=Sistema de Productos
app.version=1.0.0
app.autor=Desarrollos Inovadores S.A.
app.language=es
app.country=Mexico